import { Project, BlogPost, Author, Experience, Skill } from './types';

export const author: Author = {
  id: 'author-1',
  name: 'Hikmet Güleşli',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
  title: 'Full-Stack Developer & Sistem Mühendisi',
  bio: 'Modern web teknolojileri ile dijital ürünler geliştiriyorum. Özellikle React, Node.js ve bulut tabanlı mimariler konusunda uzmanlaşmış durumdayım. Açık kaynak projelere katkıda bulunmayı ve bilgi paylaşımını önemsiyorum.',
  location: 'İstanbul, Türkiye',
  social: {
    github: 'https://github.com/hikmetgulsesli',
    linkedin: 'https://linkedin.com/in/hikmetgulsesli',
    twitter: 'https://twitter.com/hikmetgulsesli',
    email: 'hikmet@hikmetgulsesli.com',
    website: 'https://hikmetgulsesli.com',
  },
  skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'],
};

export const projects: Project[] = [
  {
    id: 'proj-1',
    slug: 'vesta-dashboard',
    title: 'Vesta Dashboard',
    description: 'Finansal veri görselleştirme ve analiz platformu. Kullanıcıların portföy performansını gerçek zamanlı olarak izlemelerine, risk analizi yapmalarına ve yatırım kararlarını veriye dayalı şekilde almalarına olanak tanıyan kapsamlı bir dashboard çözümü.',
    shortDescription: 'Finansal veri görselleştirme ve analiz platformu',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop',
    ],
    category: 'web',
    techStack: [
      { id: 'tech-1', name: 'React', category: 'frontend' },
      { id: 'tech-2', name: 'TypeScript', category: 'frontend' },
      { id: 'tech-3', name: 'Tailwind CSS', category: 'frontend' },
      { id: 'tech-4', name: 'Node.js', category: 'backend' },
      { id: 'tech-5', name: 'PostgreSQL', category: 'database' },
      { id: 'tech-6', name: 'Docker', category: 'devops' },
    ],
    liveUrl: 'https://vesta-dashboard.vercel.app',
    githubUrl: 'https://github.com/hikmetgulsesli/vesta-dashboard',
    featured: true,
    publishedAt: '2024-01-15',
    status: 'published',
    content: '# Vesta Dashboard\n\nFinansal veri görselleştirme platformu...',
    challenges: 'Büyük miktarda gerçek zamanlı verinin etkili bir şekilde işlenmesi ve görselleştirilmesi.',
    solutions: 'WebSocket bağlantıları ve veri streaming için optimizasyonlar yapıldı.',
    results: '%40 performans artışı ve kullanıcı memnuniyetinde %60 artış.',
    client: 'Vesta Financial',
    duration: '6 ay',
    sortOrder: 1,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'proj-2',
    slug: 'sentinel-monitoring',
    title: 'Sentinel Monitoring',
    description: 'Sunucu ve uygulama izleme sistemi. Altyapı sağlığını 7/24 takip eden, anlık uyarılar ve otomatik ölçeklendirme özellikleriyle donatılmış kapsamlı bir monitoring çözümü.',
    shortDescription: 'Sunucu ve uygulama izleme sistemi',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop',
    ],
    category: 'web',
    techStack: [
      { id: 'tech-7', name: 'Next.js', category: 'frontend' },
      { id: 'tech-8', name: 'Go', category: 'backend' },
      { id: 'tech-9', name: 'InfluxDB', category: 'database' },
      { id: 'tech-10', name: 'Prometheus', category: 'devops' },
      { id: 'tech-11', name: 'Grafana', category: 'devops' },
    ],
    liveUrl: 'https://sentinel-monitor.io',
    githubUrl: 'https://github.com/hikmetgulsesli/sentinel',
    featured: true,
    publishedAt: '2023-11-20',
    status: 'published',
    content: '# Sentinel Monitoring\n\nSunucu izleme sistemi...',
    challenges: 'Yüksek hacimli metrik verilerinin düşük gecikme ile işlenmesi.',
    solutions: 'Time-series database kullanımı ve aggregation stratejileri geliştirildi.',
    results: '%99.9 uptime sağlandı, ortalama yanıt süresi %50 düştü.',
    duration: '4 ay',
    sortOrder: 2,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2023-11-20T00:00:00Z',
  },
  {
    id: 'proj-3',
    slug: 'nexus-mobile',
    title: 'Nexus Mobile',
    description: 'React Native ile geliştirilmiş, cross-platform mobil uygulama. Kullanıcıların görevlerini yönetmelerine, işbirliği yapmalarına ve üretkenliklerini artırmalarına yardımcı oluyor.',
    shortDescription: 'Cross-platform mobil uygulama',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=800&fit=crop',
    ],
    category: 'mobile',
    techStack: [
      { id: 'tech-12', name: 'React Native', category: 'mobile' },
      { id: 'tech-13', name: 'TypeScript', category: 'frontend' },
      { id: 'tech-14', name: 'Firebase', category: 'backend' },
      { id: 'tech-15', name: 'Redux', category: 'frontend' },
    ],
    liveUrl: 'https://play.google.com/store/apps/details?id=com.nexus.mobile',
    githubUrl: 'https://github.com/hikmetgulsesli/nexus-mobile',
    featured: false,
    publishedAt: '2023-09-10',
    status: 'published',
    content: '# Nexus Mobile\n\nMobil uygulama...',
    duration: '3 ay',
    sortOrder: 3,
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2023-09-10T00:00:00Z',
  },
  {
    id: 'proj-4',
    slug: 'openapi-generator',
    title: 'OpenAPI Generator CLI',
    description: 'OpenAPI spesifikasyonlarından otomatik olarak API istemcileri ve sunucu kodları üreten açık kaynak CLI aracı. TypeScript, Go, Python ve Java dillerini destekliyor.',
    shortDescription: 'OpenAPI’dan kod üreten açık kaynak CLI',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=800&fit=crop',
    ],
    category: 'open-source',
    techStack: [
      { id: 'tech-16', name: 'Node.js', category: 'backend' },
      { id: 'tech-17', name: 'TypeScript', category: 'frontend' },
      { id: 'tech-18', name: 'Commander.js', category: 'tool' },
    ],
    githubUrl: 'https://github.com/hikmetgulsesli/openapi-generator',
    featured: true,
    publishedAt: '2023-07-15',
    status: 'published',
    content: '# OpenAPI Generator CLI\n\nAçık kaynak kod üretici...',
    challenges: 'Çoklu dil desteği ve tutarlı kod üretimi.',
    solutions: 'Template engine kullanarak dil-agnostic bir mimari kuruldu.',
    results: 'GitHub\'da 2.5K yıldız ve aktif topluluk.',
    duration: '2 ay',
    sortOrder: 4,
    createdAt: '2023-07-01T00:00:00Z',
    updatedAt: '2023-07-15T00:00:00Z',
  },
  {
    id: 'proj-5',
    slug: 'ecommerce-platform',
    title: 'E-Ticaret Platformu',
    description: 'Küçük ve orta ölçekli işletmeler için tasarlanmış, özelleştirilebilir e-ticaret çözümü. Stok yönetimi, sipariş takibi ve çoklu ödeme entegrasyonları sunuyor.',
    shortDescription: 'KOBİ\'ler için e-ticaret platformu',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=800&fit=crop',
    ],
    category: 'freelance',
    techStack: [
      { id: 'tech-19', name: 'Next.js', category: 'frontend' },
      { id: 'tech-20', name: 'Stripe', category: 'backend' },
      { id: 'tech-21', name: 'PostgreSQL', category: 'database' },
      { id: 'tech-22', name: 'AWS', category: 'devops' },
    ],
    liveUrl: 'https://shop.elifyilmaz.com.tr',
    featured: false,
    publishedAt: '2023-05-20',
    status: 'published',
    content: '# E-Ticaret Platformu\n\nKOBİ e-ticaret çözümü...',
    client: 'Elif Yılmaz',
    duration: '4 ay',
    sortOrder: 5,
    createdAt: '2023-05-01T00:00:00Z',
    updatedAt: '2023-05-20T00:00:00Z',
  },
  {
    id: 'proj-6',
    slug: 'chatbot-framework',
    title: 'AI Chatbot Framework',
    description: 'LLM entegrasyonlu, özelleştirilebilir chatbot framework\'ü. Birden fazla AI sağlayıcısı destekler ve kolayca farklı senaryolara uyarlanabilir.',
    shortDescription: 'LLM entegrasyonlu chatbot framework',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=800&fit=crop',
    ],
    category: 'open-source',
    techStack: [
      { id: 'tech-23', name: 'Python', category: 'backend' },
      { id: 'tech-24', name: 'FastAPI', category: 'backend' },
      { id: 'tech-25', name: 'LangChain', category: 'tool' },
      { id: 'tech-26', name: 'Redis', category: 'database' },
    ],
    githubUrl: 'https://github.com/hikmetgulsesli/chatbot-framework',
    featured: false,
    publishedAt: '2023-03-12',
    status: 'published',
    content: '# AI Chatbot Framework\n\nLLM chatbot framework...',
    duration: '3 ay',
    sortOrder: 6,
    createdAt: '2023-03-01T00:00:00Z',
    updatedAt: '2023-03-12T00:00:00Z',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'post-1',
    slug: 'future-of-ai-agents-in-development',
    title: 'Yazılım Geliştirmede AI Agentlarının Geleceği',
    excerpt: 'AI agentlarının yazılım geliştirme süreçlerini nasıl dönüştürdüğünü ve yakın gelecekte bizi nelerin beklediğini keşfediyoruz. Kod yazma, test oluşturma ve dağıtım süreçlerinde AI\'ın rolü.',
    featuredImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=630&fit=crop',
    category: 'teknik',
    tags: ['AI', 'Yazılım Geliştirme', 'Gelecek', 'Otomasyon'],
    readTime: 8,
    publishedAt: '2024-06-15',
    status: 'published',
    content: '# AI Agentlarının Geleceği\n\nYapay zeka agentları...',
    author,
    featured: true,
    pinned: true,
    seo: {
      title: 'Yazılım Geliştirmede AI Agentlarının Geleceği',
      description: 'AI agentlarının yazılım geliştirme süreçlerini nasıl dönüştürdüğünü keşfedin.',
    },
    createdAt: '2024-06-15T00:00:00Z',
    updatedAt: '2024-06-15T00:00:00Z',
  },
  {
    id: 'post-2',
    slug: 'optimizing-react-60fps',
    title: 'React\'i 60fps Performans için Optimize Etme',
    excerpt: 'React uygulamalarında performans darboğazlarını tespit etme ve giderme stratejileri. Memoization, code splitting ve virtual DOM optimizasyonları ile akıcı kullanıcı deneyimleri.',
    featuredImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=630&fit=crop',
    category: 'teknik',
    tags: ['React', 'Performans', 'Frontend', 'Optimizasyon'],
    readTime: 12,
    publishedAt: '2024-05-28',
    status: 'published',
    content: '# React Performans Optimizasyonu\n\nReact uygulamaları...',
    author,
    featured: true,
    pinned: false,
    createdAt: '2024-05-28T00:00:00Z',
    updatedAt: '2024-05-28T00:00:00Z',
  },
  {
    id: 'post-3',
    slug: 'rust-vs-wasm-performance',
    title: 'Rust vs WASM: Performans Sınırı',
    excerpt: 'WebAssembly ve Rust\'ın browser tabanlı hesaplama için performans karşılaştırması. Gerçek dünya benchmarkları ve hangi senaryolarda hangi teknolojinin tercih edilmesi gerektiği.',
    featuredImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&h=630&fit=crop',
    category: 'teknik',
    tags: ['Rust', 'WebAssembly', 'Performans', 'Browser'],
    readTime: 10,
    publishedAt: '2024-04-12',
    status: 'published',
    content: '# Rust vs WASM\n\nWebAssembly performansı...',
    author,
    featured: false,
    pinned: false,
    createdAt: '2024-04-12T00:00:00Z',
    updatedAt: '2024-04-12T00:00:00Z',
  },
  {
    id: 'post-4',
    slug: 'real-time-websockets-hooks',
    title: 'Realtime WebSocket\'ler için Custom Hooks',
    excerpt: 'Karmaşık socket durumlarını ana thread\'i boğmadan yönetmek için React custom hookları. Bağlantı yönetimi, reconnection stratejileri ve hata handling.',
    featuredImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=630&fit=crop',
    category: 'teknik',
    tags: ['React', 'WebSocket', 'Hooks', 'Realtime'],
    readTime: 7,
    publishedAt: '2024-03-05',
    status: 'published',
    content: '# WebSocket Hooks\n\nRealtime bağlantılar...',
    author,
    featured: false,
    pinned: false,
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: 'post-5',
    slug: 'death-of-minimalism-ui',
    title: 'UI\'da Minimalizmin Ölümü',
    excerpt: 'Neden yoğun ve veri-çoklu arayüzlerin geri döndüğünü tartışıyoruz. Bilgi mimarisi, görsel hiyerarşi ve modern UI trendleri.',
    featuredImage: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=1200&h=630&fit=crop',
    category: 'tasarim',
    tags: ['UI', 'Tasarım', 'Trend', 'Minimalizm'],
    readTime: 6,
    publishedAt: '2024-02-20',
    status: 'published',
    content: '# Minimalizmin Ölümü\n\nUI trendleri değişiyor...',
    author,
    featured: false,
    pinned: false,
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'post-6',
    slug: 'from-bootcamp-to-senior',
    title: 'Bootcamp\'ten Seniorlığa: 3 Yıllık Yolculuk',
    excerpt: 'Yazılım geliştirme bootcamp\'inden kıdemli mühendisliğe geçiş hikayem. Öğrenme stratejileri, kariyer tavsiyeleri ve teknik yetkinlik geliştirme.',
    featuredImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&h=630&fit=crop',
    category: 'kariyer',
    tags: ['Kariyer', 'Bootcamp', 'Senior', 'Öğrenme'],
    readTime: 9,
    publishedAt: '2024-01-10',
    status: 'published',
    content: '# Bootcamp\'ten Seniorlığa\n\nKariyer yolculuğu...',
    author,
    featured: false,
    pinned: false,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
];

export const experiences: Experience[] = [
  {
    id: 'exp-1',
    title: 'Senior Full-Stack Developer',
    company: 'TechCorp İstanbul',
    companyUrl: 'https://techcorp.example.com',
    location: 'İstanbul, Türkiye',
    startDate: '2022-03',
    current: true,
    description: 'Fintech sektöründe kurumsal ölçekte web uygulamaları geliştiriyorum. Mikroservis mimarileri, CI/CD pipeline\'ları ve bulut tabanlı dağıtımlar konusunda uzmanlaştım.',
    type: 'full-time',
    achievements: [
      'Mikroservis mimarisine geçiş projesini yönettim',
      'Ekip içi mentorluk programı başlattım',
      'Deploy süresini %60 kısaltan CI/CD pipeline kurdum',
    ],
    createdAt: '2022-03-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exp-2',
    title: 'Full-Stack Developer',
    company: 'StartupXYZ',
    companyUrl: 'https://startupxyz.example.com',
    location: 'İstanbul, Türkiye',
    startDate: '2020-06',
    endDate: '2022-02',
    current: false,
    description: 'Erken aşama bir startup\'ta React ve Node.js ile tam yığın geliştirme yaptım. Ürün geliştirme sürecinin tüm aşamalarında yer aldım.',
    type: 'full-time',
    achievements: [
      'Sıfırdan MVP geliştirdim',
      '500+ aktif kullanıcıya ulaşan ürün lansmanı',
      '3 kişilik ekibi yönettim',
    ],
    createdAt: '2020-06-01T00:00:00Z',
    updatedAt: '2022-02-01T00:00:00Z',
  },
  {
    id: 'exp-3',
    title: 'Junior Frontend Developer',
    company: 'WebAgency Pro',
    location: 'Ankara, Türkiye',
    startDate: '2019-01',
    endDate: '2020-05',
    current: false,
    description: 'Dijital ajans ortamında çeşitli müşteri projelerinde frontend geliştirme yaptım. HTML, CSS, JavaScript ve jQuery ile temel web teknolojilerini öğrendim.',
    type: 'full-time',
    achievements: [
      '20+ müşteri projesinde frontend geliştirdim',
      'Responsive tasarım uzmanlığı kazandım',
    ],
    createdAt: '2019-01-01T00:00:00Z',
    updatedAt: '2020-05-01T00:00:00Z',
  },
];

export const skills: Skill[] = [
  // Frontend
  { id: 'skill-1', name: 'React', icon: '⚛️', proficiency: 95, category: 'frontend', years: 5, projects: 20 },
  { id: 'skill-2', name: 'TypeScript', icon: '📘', proficiency: 90, category: 'frontend', years: 4, projects: 18 },
  { id: 'skill-3', name: 'Next.js', icon: '▲', proficiency: 88, category: 'frontend', years: 3, projects: 12 },
  { id: 'skill-4', name: 'Tailwind CSS', icon: '🎨', proficiency: 92, category: 'frontend', years: 3, projects: 15 },
  { id: 'skill-5', name: 'Vue.js', icon: '💚', proficiency: 75, category: 'frontend', years: 2, projects: 5 },
  // Backend
  { id: 'skill-6', name: 'Node.js', icon: '🟢', proficiency: 88, category: 'backend', years: 5, projects: 16 },
  { id: 'skill-7', name: 'Python', icon: '🐍', proficiency: 80, category: 'backend', years: 3, projects: 8 },
  { id: 'skill-8', name: 'Go', icon: '🔵', proficiency: 70, category: 'backend', years: 2, projects: 4 },
  { id: 'skill-9', name: 'FastAPI', icon: '⚡', proficiency: 78, category: 'backend', years: 2, projects: 5 },
  // Database
  { id: 'skill-10', name: 'PostgreSQL', icon: '🐘', proficiency: 85, category: 'database', years: 4, projects: 14 },
  { id: 'skill-11', name: 'MongoDB', icon: '🍃', proficiency: 75, category: 'database', years: 3, projects: 8 },
  { id: 'skill-12', name: 'Redis', icon: '🔴', proficiency: 80, category: 'database', years: 3, projects: 10 },
  // DevOps
  { id: 'skill-13', name: 'Docker', icon: '🐳', proficiency: 85, category: 'devops', years: 4, projects: 15 },
  { id: 'skill-14', name: 'AWS', icon: '☁️', proficiency: 78, category: 'devops', years: 3, projects: 10 },
  { id: 'skill-15', name: 'CI/CD', icon: '🔄', proficiency: 82, category: 'devops', years: 3, projects: 12 },
  // Mobile
  { id: 'skill-16', name: 'React Native', icon: '📱', proficiency: 72, category: 'mobile', years: 2, projects: 3 },
  // Design
  { id: 'skill-17', name: 'UI/UX Tasarım', icon: '🎯', proficiency: 70, category: 'design', years: 4, projects: 10 },
  { id: 'skill-18', name: 'Figma', icon: '✏️', proficiency: 75, category: 'design', years: 3, projects: 8 },
  // Soft Skills
  { id: 'skill-19', name: 'Takım Liderliği', icon: '👥', proficiency: 85, category: 'soft-skills', years: 3 },
  { id: 'skill-20', name: 'Proje Yönetimi', icon: '📊', proficiency: 80, category: 'soft-skills', years: 3 },
];

export const categories = [
  { category: 'teknik', label: 'Teknik', count: 4 },
  { category: 'kariyer', label: 'Kariyer', count: 1 },
  { category: 'kisisel', label: 'Kişisel', count: 0 },
  { category: 'tutorial', label: 'Tutorial', count: 0 },
  { category: 'tasarim', label: 'Tasarım', count: 1 },
];

export const projectCategories = [
  { category: 'web', label: 'Web', count: 2 },
  { category: 'mobile', label: 'Mobil', count: 1 },
  { category: 'open-source', label: 'Açık Kaynak', count: 2 },
  { category: 'freelance', label: 'Freelance', count: 1 },
];
